### PR TITLE
OOP - Milestone: user interface

### PR DESCRIPTION
**Pull request by jebitok-dev**
In this milestone I:
- set-up new branch and project folders
- created the user interface of the Tic Tac Toe

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Status: Changes Required**
Hello team,
Great work on the project so far, but we have to make a few more changes to get this milestone Approved. Let me break down the changes for you.
[REQUIRED]
- [ ] This branch has conflicts please fix it.


- [ ] User must be able to enter a number (move).
- [ ] Game inform the player **if the selected move is invalid.**
- [ ] Game **displays board after the player move**.
- [ ] **Game repeats all actions for the next player's move.**


_Implementation details_
- [ ] A loop is needed in this game.
- [ ] Inside the loop, you should call actions repeated for each move.
Eg:

>  game_on = true
>   => initial instructions for player
> while game_on
>        =>loop for each move
>   if winner # and/or draw (the exact condition in this milestone is not important)
>     game_on = false
>   end
> end

Keep up with the efforts towards this project, you are almost there.
Cheers!!
Rindra Josia

**Comment by jebitok-dev** [comment]
I will fix the conflict after the milestone has been approved to avoid merging the feature-branch to develop before everything is checked.

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Status: Changes Required**
Hey! Good job for the work you have done so far.
However, you still have not implemented all the changes required. Kindly work on all the feedback given. It is important to work on any feedback given by a TSE before requesting another review.

**REQUIRED**
- [ ] Game **must** inform the player if the selected move is invalid.


- [ ] Game **must** display the board after each player move.
- [ ] Game repeats all actions for the next player's move (Until the game is a draw or there is a winner: use a loop for that).

Keep up with the efforts towards this project, you are almost there.
Happy coding!!!!
Rindra Josia

**Comment by jebitok-dev** [comment]
is the board suppose to display on the user interface milestone? Thought I'll implement that on the game logic.

**Review by Georjane — APPROVED** [review]
## Status: PR Approved ✔️ ✔️
### Hi Team 🙌
Nice work on the User Interface Milestone. It's a thumbs up for me. 👍 
You can go ahead and merge this PR. 

Goodluck on the next milestones and Happy Coding 💻

**Pull request merged**
